// <auto-generated />
using System;
using CoreTShirtStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreTShirtStore.Migrations
{
    [DbContext(typeof(TShirtContext))]
    [Migration("20210925173211_include-message")]
    partial class includemessage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreTShirtStore.Models.Sponsor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SalesRegion")
                        .HasColumnType("int");

                    b.Property<int?>("TShirtID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TShirtID");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("CoreTShirtStore.Models.TShirt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isTightFit")
                        .HasColumnType("bit");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TShirts");
                });

            modelBuilder.Entity("CoreTShirtStore.Models.Sponsor", b =>
                {
                    b.HasOne("CoreTShirtStore.Models.TShirt", null)
                        .WithMany("Sponsors")
                        .HasForeignKey("TShirtID");
                });

            modelBuilder.Entity("CoreTShirtStore.Models.TShirt", b =>
                {
                    b.Navigation("Sponsors");
                });
#pragma warning restore 612, 618
        }
    }
}
